### ISSUE TITLE
Upstream merge/Update policy

### ISSUE THREAD

**Issue by simonsan** [tapan288/breeze-svelte#2]
Could you PR the changes needed upstream, or could you give information on how you plan to update/the update policy of yours?

How is it set up, can your package go out-of-sync with the upstream breeze package?

**Comment by tapan288** [comment]
@simonsan, I found a simple solution to sync changes with the breeze package.
- Fork the package into my account
- Add that repo as an origin => `git remote add breeze https://github.com/tapan288/breeze.git`
- Pull the specific branch =>  `git pull breeze 1.x`
- Might throw an error, to fix it: `git pull breeze 1.x --allow-unrelated-histories`
- Make the changes, fix merge conflicts and then push it
